M48
; DRILL file KiCad 10.0.3 date 2026-07-01T22:05:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-01T22:05:26+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X123.444Y-58.674
X123.444Y-92.075
X193.802Y-58.928
X193.802Y-92.075
M30
